name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@5a6d08a067e0528f2b3d66aa168ffdcff8de68f9 # main

  cgl:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          # We use the minimum supported PHP version
          php-version: 8.2 # renovate-ignore
          tools: composer:v2, composer-require-checker, composer-unused
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@26d8a556604053a9612623447203a691f406fbe6 # v4

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint Editorconfig
        run: composer lint:editorconfig
      - name: Lint PHP
        run: composer lint:php

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
