name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: 'Create release'
    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@cd9d7395b05159994d09371388e4f804fafd82c2 # 1.0.1
